server:
  port: 8081
spring:
  application:
    name: orcat
  datasource:
    url: jdbc:postgresql://localhost:1111/orcat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format-sql: true